---
title: Game Mode
description: Enables Windows Game Mode
privilege: TrustedInstaller
actions:

  - !registryValue: {path: 'HKCU\Software\Microsoft\GameBar', value: 'AllowAutoGameMode', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\GameBar', value: 'AutoGameModeEnabled', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\GameBar', value: 'AllowAutoGameMode', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\GameBar', value: 'AutoGameModeEnabled', type: REG_DWORD, data: '1'}
