---
title: mithen-static-edition
description: mithen-static-edition
privilege: TrustedInstaller
actions:

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'EditionSubManufacturer', type: REG_SZ, data: 'Mithen'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'EditionSubstring', type: REG_SZ, data: 'Mithen'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'EditionSubVersion', type: REG_SZ, data: 'MithenOS'}


  # === Causes Network Sharing/Computer Name issues
  # - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\ComputerName\ComputerName', value: 'ComputerName', type: REG_SZ, data: 'Mithen-PC'}
  # - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\ComputerName\ActiveComputerName', value: 'ComputerName', type: REG_SZ, data: 'Mithen-PC'}