blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/catchem88/mithen-os/discussions
    about: For general questions or technical support, please use the Discussions page